name: Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      
    - name: 'Setup .NET 9 SDK'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: 'Build Solution'
      run: |
        dotnet restore ./AuthService.API/AuthService.API.csproj
        dotnet build ./AuthService.API/AuthService.API.csproj --configuration Release

    - name: 'Apply Database Migrations' 
      run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update -c AppDbContext -p ./AuthService.API/AuthService.API.csproj -s ./AuthService.API/AuthService.API.csproj
    
    - name: 'Publish'
      run: |
        dotnet publish ./AuthService.API/AuthService.API.csproj --configuration Release --no-build --output './publish'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: file-service-auth
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
